
FROM public.ecr.aws/docker/library/python:3.12.0-slim-bullseye

# Install Lambda Web Adapter: https://github.com/awslabs/aws-lambda-web-adapter
COPY --from=public.ecr.aws/awsguru/aws-lambda-adapter:0.8.4 /lambda-adapter /opt/extensions/lambda-adapter

WORKDIR /app

COPY ./requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

COPY ./api /app/api

CMD ["uvicorn", "api.app:app", "--host", "0.0.0.0", "--port", "8080"]
